/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package new1encryptdecrypt;

import javax.swing.JOptionPane;



/**
 *
 * @author Sushant ADMIN
 */
public class EncDecrypt extends javax.swing.JFrame {

    /**
     * Creates new form Encrypt_Decrypt
     */
    String dataInput;
    long keyInput = 0;
    long decryptKey = 0;
    String encryptData;
    String decryptData;
    //creating the object of then
    then objThen = new then();

    public EncDecrypt() {
        initComponents();
        setTitle("Encrypt+ Decrypt (@ NanoSoft pvt Limited)");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textField1 = new java.awt.TextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textInput = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        decryptClick = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        decryptDisplay = new javax.swing.JTextArea();
        jTextField2 = new javax.swing.JTextField();
        encyptClick = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        decrypKey = new javax.swing.JTextField();
        enKey = new java.awt.TextField();

        jLabel1.setText("jLabel1");

        textField1.setText("textField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textInput.setColumns(20);
        textInput.setRows(5);
        jScrollPane2.setViewportView(textInput);

        jTextField1.setBackground(new java.awt.Color(204, 204, 204));
        jTextField1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 102, 255));
        jTextField1.setText("Enter the word to Encrypt and Decrypt");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        decryptClick.setBackground(new java.awt.Color(255, 102, 204));
        decryptClick.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        decryptClick.setForeground(new java.awt.Color(255, 0, 0));
        decryptClick.setText("Decrypt");
        decryptClick.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        decryptClick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decryptClickActionPerformed(evt);
            }
        });

        decryptDisplay.setColumns(20);
        decryptDisplay.setRows(5);
        decryptDisplay.setText("Please enter your key!! Your Decrypted Text is seen here!!");
        jScrollPane1.setViewportView(decryptDisplay);

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(204, 204, 255));
        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField2.setText("Enter your Key: ");

        encyptClick.setBackground(new java.awt.Color(204, 255, 255));
        encyptClick.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        encyptClick.setForeground(new java.awt.Color(204, 204, 204));
        encyptClick.setText("Encrypt");
        encyptClick.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        encyptClick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encyptClickActionPerformed(evt);
            }
        });

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(204, 204, 255));
        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField4.setText("Enter your Key: ");

        decrypKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decrypKeyActionPerformed(evt);
            }
        });

        enKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enKeyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(decrypKey, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(decryptClick, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(20, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(enKey, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(encyptClick, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30)))
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enKey, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(encyptClick, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(decrypKey, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(decryptClick, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void decrypKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decrypKeyActionPerformed
//        decryptKey = Integer.parseInt(decrypKey.getText());
    }//GEN-LAST:event_decrypKeyActionPerformed

    private void encyptClickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encyptClickActionPerformed
//        jTextField3.setText("");
//        textInput.setText("");

        if (enKey.getText() != null) {

            keyInput = Long.parseLong(enKey.getText());
            if (keyInput > 1000) {  // make system to encrypt if textInput is not null
                if (textInput.getText() != null) {
                    dataInput = textInput.getText();
                    
                    if(dataInput == null){
                    JOptionPane.showMessageDialog(null, "Please Enter The text here To Encrypt!! ","Message", JOptionPane.INFORMATION_MESSAGE);

                    }else{
                    encryptData = objThen.encryptcon(dataInput, keyInput);
                    textInput.setText("");
                    //also see as the big integer key is used it is not valid so,use it as long data type for key
                    
                    textInput.setText(String.valueOf(encryptData));
                    }
                    
                } else {
                    //textInput.setText("Please Enter The text here To Encrypt!!");
                    JOptionPane.showMessageDialog(null, "Please Enter The text here To Encrypt!! ","Message", JOptionPane.INFORMATION_MESSAGE);
  
                }
            } else {
                 
                //textInput.setText("Key must be greater than 1000!!\n--->The greater key input Can make Your Document more Secure (@By NanoSoft...)");
                JOptionPane.showMessageDialog(null, "Key must be greater than 1000!!\n--->The greater key input Can make Your Document more Secure (@By NanoSoft...) ","Message", JOptionPane.INFORMATION_MESSAGE);

            }

        } else {
            enKey.setText("Enter the key except 0");
        }
        enKey.setText("");
    }//GEN-LAST:event_encyptClickActionPerformed

    private void decryptClickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decryptClickActionPerformed

        dataInput = textInput.getText();
        
        decryptKey = Long.parseLong(decrypKey.getText());
        decryptData = objThen.decryptcon(dataInput, decryptKey);
        if (decryptData == null) {
            decrypKey.setText("Enter key not match!!!");

        } else {
            decrypKey.setText("Enter key match!!!");
            decryptDisplay.setText(decryptData);
        }


    }//GEN-LAST:event_decryptClickActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void enKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enKeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enKeyActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField decrypKey;
    private javax.swing.JButton decryptClick;
    private javax.swing.JTextArea decryptDisplay;
    private java.awt.TextField enKey;
    private javax.swing.JButton encyptClick;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private java.awt.TextField textField1;
    private javax.swing.JTextArea textInput;
    // End of variables declaration//GEN-END:variables
}
